### [PyCharm Setup Video](https://www.youtube.com/watch?v=TGQcDaZ56ao&list=PLS1QulWo1RIa7D1O6skqDQ-JZ1GGHKK-K&index=3)

- cv2.imread('path', IMREAD_) # numpy.ndarray object
    - cv2.IMREAD_COLOR
    - cv2.IMREAD_GRAYSCALE
- cv2.imshow('image', img)
- cv2.waitKey(0) & 0xFF
- cv2.destroyAllWindows()
- cv2.imwrite('name', img))

------

In [1]:
import cv2
import numpy as np
import pandas as pd
import seaborn as sns
from PIL import Image

# Misc
import os
import sys
import warnings
warnings.filterwarnings(action='ignore')

# Preset data display
pd.options.display.max_seq_items = 1000
pd.options.display.max_rows =1000
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_colwidth', 500)

# Set notebook colors and palette
flatui = ['#9b59b6', '#3498db', '#95a5a6', '#e74c3c', '#34495e', '#2ecc71']
sns.set_palette(flatui)
sns.palplot(sns.color_palette(flatui))
sns.set_style('white')
sns.set_color_codes(palette='deep')
# Favorite code to use: #34995e

print('='*50)
print(f"OpenCV Version: {cv2.__version__}")
print(f"Python {sys.version}")

OpenCV Version: 4.0.1
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]


### Read an image

cv2.imread() flag parameter which specifies the way image should be read
- cv2.IMREAD_COLOR (1): loads a color image
- cv2.IMREAD_GRAYSCALE (0): loads image in grayscale
- cv2.IMREAD_UNCHANGED (-1): loads image as such including alpha channel

In [2]:
img = cv2.imread('images/lena.jpg', cv2.IMREAD_GRAYSCALE)
print(img) # produces a matrix

[[163 162 161 ... 170 154 130]
 [162 162 162 ... 173 155 126]
 [162 162 163 ... 170 155 128]
 ...
 [ 43  42  51 ... 103 101  99]
 [ 41  42  55 ... 103 105 106]
 [ 42  44  57 ... 102 106 109]]


In [3]:
type(img)

numpy.ndarray

### Display image in grayscale mode

In [4]:
cv2.imshow('image', img)
# cv2.waitKey(5000) # show for 5 seconds 
cv2.waitKey(0) # exit to close
cv2.destroyAllWindows()

### Write an image to a file

In [6]:
cv2.imwrite('images/lena_copy.png', img) # save as png

True

In [8]:
cv2.imshow('image', img)
k = cv2.waitKey(0) & 0xFF # exit to close, use mask 0xFF notation for 64bit computer

# Open image and save if pressed 's' - the python program hangs so destroy the window after 3 seconds
if k == 27: # 27 = escape key
    cv2.destroyAllWindows()
elif k == ord('s'):
    cv2.imwrite('images/another_copy_lena.png', img)
    cv2.waitKey(3000) & 0xFF
    cv2.destroyAllWindows()